name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: install node
        run: make install

      - name: project setup
        run: make setup

      - name: run tests
        run: make test

      - name: run lint
        run: make lint

      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
